config/routes.rb
Lab6::Application.routes.draw do

  get "sessions/index"
  root 'films#index'

  get "search/by_film"
  get "search/by_film_result"
  get "search/by_cinema"
  get "search/by_cinema_result"
  get "search/by_session"
  get "search/by_session_result"

  resources :films

  resources :cinemas

  resources :sessions
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
	has_many :sessions, dependent: :destroy
	has_many :films, through: :sessions

	def self.search(search)
	    if search
	    	find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	    else
	    	find(:all)
	    end
	end
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :sessions, dependent: :destroy
	has_many :cinemas, through: :sessions

	def self.search(search)
	    if search
	    	find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	    else
	    	find(:all)
	    end
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :film
  belongs_to :cinema

	def self.search(from, to)
	    if from && to
	    	find(:all, :conditions => ['start >= ? AND end <= ?', from, to])
	    else
	    	find(:all)
	    end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def new
		@cinema = Cinema.new
	end

    def create
    	@cinema = Cinema.new(cinema_params)
 
        if @cinema.save
            redirect_to @cinema
	    else
	        render 'new'
	    end
    end

	def edit
	    @cinema = Cinema.find(params[:id])
	end

	def update
	    @cinema = Cinema.find(params[:id])
	 
	    if @cinema.update(cinema_params)
	        redirect_to @cinema
	    else
	        render 'edit'
	    end
	end

    def show
        @cinema = Cinema.find(params[:id])
    end

    def index
        @cinemas = Cinema.all
    end

	def destroy
	  	@cinema = Cinema.find(params[:id])
	  	@cinema.destroy
	 
	  	redirect_to cinemas_path
	end

    private
	    def cinema_params
	        params.require(:cinema).permit(:name, :description, :address)
	    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def new
		@film = Film.new
	end

    def create
    	@film = Film.new(film_params)
 
        if @film.save
            redirect_to @film
	    else
	        render 'new'
	    end
    end

	def edit
	    @film = Film.find(params[:id])
	end

	def update
	    @film = Film.find(params[:id])
	 
	    if @film.update(film_params)
	        redirect_to @film
	    else
	        render 'edit'
	    end
	end

    def show
        @film = Film.find(params[:id])
    end

	def index
        @films = Film.all
    end

	def destroy
	  	@film = Film.find(params[:id])
	  	@film.destroy
	 
	  	redirect_to films_path
	end

    private
	    def film_params
	        params.require(:film).permit(:name, :description)
	    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def by_film
  end

  def by_film_result
	  if params[:search] && params[:search] != nil && params[:search] != ""
          @films = Film.search(params[:search])
          if @films != nil && @films.size > 0
      	      @film = @films.first
	          @sessions = Session.where(film_id: @film.id)
	      else
	      	  redirect_to search_by_film_path
	      end
	  else
	      redirect_to search_by_film_path
	  end
  end

  def by_session
  end

  def by_session_result
	  if params[:from] && params[:from] != nil && params[:from] != "" && params[:to] && params[:to] != nil && params[:to] != ""
	  	  @from = DateTime.strptime(params[:from], "%Y-%m-%d %H:%M:%S").to_i
          @to = DateTime.strptime(params[:to], "%Y-%m-%d %H:%M:%S").to_i
  	      @sessions = Session.search(params[:from].gsub(/[-: ]/, ''), params[:to].gsub(/[-: ]/, ''))
	  else
	      redirect_to search_by_session_path
	  end
  end

  def by_cinema
  end

  def by_cinema_result
	  if params[:search] && params[:search] != nil && params[:search] != ""
          @cinemas = Cinema.search(params[:search])
          if @cinemas != nil && @cinemas.size > 0
      	      @cinema = @cinemas.first
	          @sessions = Session.where(cinema_id: @cinema.id)
	      else
	      	  redirect_to search_by_cinema_path
	      end
	  else
	      redirect_to search_by_cinema_path
	  end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
    http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def new
		@session = Session.new
        @films = Film.all
        @cinemas = Cinema.all
	end

    def create
    	@session = Session.new(session_params)
 
        if @session.save
            redirect_to @session
	    else
	        render 'new'
	    end
    end

	def edit
	    @session = Session.find(params[:id])
        @cinema = Cinema.find(@session.cinema_id)
        @film = Film.find(@session.film_id)
	end

	def update
	    @session = Session.find(params[:id])
	 
	    if @session.update(session_params)
	        redirect_to @session
	    else
	        render 'edit'
	    end
	end

    def show
        @session = Session.find(params[:id])
        @cinema = Cinema.find(@session.cinema_id)
        @film = Film.find(@session.film_id)
    end

	def index
        @sessions = Session.all
    end

	def destroy
	  	@session = Session.find(params[:id])
	  	@session.destroy
	 
	  	redirect_to sessions_path
	end

    private
	    def session_params
	        params.require(:session).permit(:start, :end, :cinema_id, :film_id)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cinemas/edit.html.erb
<h1>Редактирование кинотеатра</h1>
 
<%= form_for :cinema, url: cinema_path(@cinema), method: :patch do |f| %>
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :описание %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :адрес %><br>
    <%= f.text_area :address %>
  </p>
 
  <p>
    <%= f.submit :обновить%>
  </p>
<% end %>

<%= link_to 'Назад', cinemas_path %>

app/views/cinemas/index.html.erb
<h1>Все кинотеатры</h1>
<%= link_to 'Перейти к просмотру фильмов', films_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Перейти к просмотру сеансов', sessions_path %><br><br>
 
<%= link_to 'Создать кинотеатр', new_cinema_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Поиск по кинотеатрам', search_by_cinema_path %><br><br>

<table>
  <tr>
    <th>Название</th>
    <th>Описание</th>
    <th>Адрес</th>
  </tr>
 
  <% @cinemas.each do |cinema| %>
    <tr>
      <td><%= cinema.name %></td>
      <td><%= cinema.description %></td>
      <td><%= cinema.address %></td>
      <td><%= link_to 'Просмотреть', cinema_path(cinema) %></td>
      <td><%= link_to 'Редактировать', edit_cinema_path(cinema) %></td>
      <td><%= link_to 'Удалить', cinema_path(cinema),
                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cinemas/new.html.erb
<h1>Добавить кинотеатр</h1>

<%= form_for :cinema, url: cinemas_path do |f| %>
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :описание %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :адрес %><br>
    <%= f.text_area :address %>
  </p>
  </p>
 
  <p>
    <%= f.submit :сохранить%>
  </p>
<% end %>

<%= link_to 'Назад', cinemas_path %>

app/views/cinemas/show.html.erb
<p>
  <h1><%= @cinema.name %></h1>
  <strong>Описание:</strong>
  <%= @cinema.description %><br>
  <strong>Адрес:</strong>
  <%= @cinema.address %><br>
</p>

<%= link_to 'Назад', cinemas_path %>
<%= link_to 'Редактировать', edit_cinema_path(@cinema) %>

app/views/films/edit.html.erb
<h1>Редактирование фильма</h1>
 
<%= form_for :film, url: film_path(@film), method: :patch do |f| %>
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :описание %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :обновить%>
  </p>
<% end %>

<%= link_to 'Назад', films_path %>

app/views/films/index.html.erb
<h1>Все фильмы</h1>
<%= link_to 'Перейти к просмотру кинотеатров', cinemas_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Перейти к просмотру сеансов', sessions_path %><br><br>
 
<%= link_to 'Создать фильм', new_film_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Поиск по фильму', search_by_film_path %><br><br>

<table>
  <tr>
    <th>Название</th>
    <th>Описание</th>
  </tr>
 
  <% @films.each do |film| %>
    <tr>
      <td><%= film.name %></td>
      <td><%= film.description %></td>
      <td><%= link_to 'Просмотреть', film_path(film) %></td>
      <td><%= link_to 'Редактировать', edit_film_path(film) %></td>
      <td><%= link_to 'Удалить', film_path(film),
                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/films/new.html.erb
<h1>Добавить фильм</h1>

<%= form_for :film, url: films_path do |f| %>
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :описание %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :сохранить%>
  </p>
<% end %>

<%= link_to 'Назад', films_path %>

app/views/films/show.html.erb
<p>
  <h1><%= @film.name %></h1>
  <strong>Описание:</strong>
  <%= @film.description %><br>
</p>

<%= link_to 'Назад', films_path %>
<%= link_to 'Редактировать', edit_film_path(@film) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/by_cinema.html.erb
<h1>Поиск по кинотеатрам </h1>
<%= link_to 'Перейти к просмотру кинотеатров', cinemas_path %><br><br>

<%= form_tag(search_by_cinema_result_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
        <%= text_field_tag :search, params[:search], class: "span2", 
            placeholder: "Введите название кинотеатра"%>
        <%= submit_tag "Искать", :name => nil %>
    </div>
<% end %>

app/views/search/by_cinema_result.html.erb
<h1>Результат поиска</h1>
<%= link_to 'Перейти к просмотру кинотеатров', cinemas_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Перейти к поиску по кинотеатрам', search_by_cinema_path %><br><br>

<h4><%= @cinema.name %><br>
<%= @cinema.description %><br>
<%= @cinema.address %><br><br></h4>
<table>
  <tr>
    <th>Название фильма</th>
    <th>Начало сеанса</th>
    <th>Окончание сеанса</th>
  </tr>
 
  <% @sessions.each do |session| %>
    <tr>
      <td><%= session.film.name %></td>
      <td><%= session.start %></td>
      <td><%= session.end %></td>
    </tr>
  <% end %>
</table>

app/views/search/by_film.html.erb
<h1>Поиск по фильмам </h1>
<%= link_to 'Перейти к просмотру фильмов', films_path %><br><br>

<%= form_tag(search_by_film_result_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
        <%= text_field_tag :search, params[:search], class: "span2", 
            placeholder: "Введите название фильма"%>
        <%= submit_tag "Искать", :name => nil %>
    </div>
<% end %>

app/views/search/by_film_result.html.erb
<h1>Результат поиска</h1>
<%= link_to 'Перейти к просмотру фильмов', films_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Перейти к поиску по фильмам', search_by_film_path %><br><br>

<h4><%= @film.name %><br>
<%= @film.description %><br><br></h4>
<table>
  <tr>
    <th>Название кинотеатра</th>
    <th>Начало сеанса</th>
    <th>Окончание сеанса</th>
  </tr>
 
  <% @sessions.each do |session| %>
    <tr>
      <td><%= session.cinema.name %></td>
      <td><%= session.start %></td>
      <td><%= session.end %></td>
    </tr>
  <% end %>
</table>

app/views/search/by_session.html.erb
<h1>Поиск по сеансам </h1>
<%= link_to 'Перейти к просмотру сеансов', sessions_path %><br><br>

<%= form_tag(search_by_session_result_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
        <%= datetime_field_tag :from, params[:from], class: "span2", 
            placeholder: "YYYY-MM-DD hh:mm:ss"%>
        <%= datetime_field_tag :to, params[:to], class: "span2", 
            placeholder: "YYYY-MM-DD hh:mm:ss"%>
        <%= submit_tag "Искать", :name => nil %>
    </div>
<% end %>

app/views/search/by_session_result.html.erb
<h1>Результат поиска </h1>
<%= link_to 'Перейти к просмотру сеансов', sessions_path %>
&nbsp;&nbsp;&nbsp;<%= link_to 'Перейти к поиску по сеансам', search_by_session_path %><br><br>

<h4>В период с <%= @from %> по <%= @to %>:</h4>

<table>
  <tr>
    <th>Название фильма</th>
    <th>Название кинотеатра</th>
    <th>Начало сеанса</th>
    <th>Окончание сеанса</th>
  </tr>
 
  <% @sessions.each do |session| %>
    <tr>
      <td><%= session.film.name %></td>
      <td><%= session.cinema.name %></td>
      <td><%= session.start %></td>
      <td><%= session.end %></td>
    </tr>
  <% end %>